Dockerfile
==========

Dockerfile is a programming language created in 2013.
 https://pldb.io/concepts/../lists/explorer.html#searchBuilder=%7B%22criteria%22%3A%5B%7B%22condition%22%3A%22%3D%22%2C%22data%22%3A%22appeared%22%2C%22origData%22%3A%22appeared%22%2C%22tags%22%3A%22num%22%2C%22value%22%3A%5B%222013%22%5D%7D%5D%2C%22logic%22%3A%22AND%22%7D

#739 on PLDB
11 Years Old
340k Repos

- Dockerfile website
 https://docs.docker.com/engine/reference/builder/
- There are at least 339,978 Dockerfile repos on GitHub
- Dockerfile first developed in Docker, Inc.
- Dockerfile on Twitter
 https://twitter.com/docker
- The  Google BigQuery Public Dataset GitHub snapshot shows 20k users using Dockerfile in 26k repos on GitHub
- Dockerfile LSP implementation
- Monaco package for syntax highlighting Dockerfile
- GitHub supports syntax highlighting for Dockerfile

# This file describes the standard way to build Docker, using docker
docker-version 0.4.2
from	ubuntu:12.04
maintainer	Solomon Hykes &lt;solomon@dotcloud.com&gt;
# Build dependencies
run	apt-get install -y -q curl
run	apt-get install -y -q git
# Install Go
run	curl -s https://go.googlecode.com/files/go1.1.1.linux-amd64.tar.gz | tar -v -C /usr/local -xz
env	PATH	/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
env	GOPATH	/go
env	CGO_ENABLED 0
run	cd /tmp &amp;&amp; echo &#39;package main&#39; &gt; t.go &amp;&amp; go test -a -i -v
# Download dependencies
run	PKG=github.com/kr/pty REV=27435c699;		 git clone http://$PKG /go/src/$PKG &amp;&amp; cd /go/src/$PKG &amp;&amp; git checkout -f $REV
run	PKG=github.com/gorilla/context/ REV=708054d61e5; git clone http://$PKG /go/src/$PKG &amp;&amp; cd /go/src/$PKG &amp;&amp; git checkout -f $REV
run	PKG=github.com/gorilla/mux/ REV=9b36453141c;	 git clone http://$PKG /go/src/$PKG &amp;&amp; cd /go/src/$PKG &amp;&amp; git checkout -f $REV
# Run dependencies
run	apt-get install -y iptables
# lxc requires updating ubuntu sources
run	echo &#39;deb http://archive.ubuntu.com/ubuntu precise main universe&#39; &gt; /etc/apt/sources.list
run	apt-get update
run	apt-get install -y lxc
run	apt-get install -y aufs-tools
# Upload docker source
add	.       /go/src/github.com/dotcloud/docker
# Build the binary
run	cd /go/src/github.com/dotcloud/docker/docker &amp;&amp; go install -ldflags &quot;-X main.GITCOMMIT &#39;??&#39; -d -w&quot;
env	PATH	/usr/local/go/bin:/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
cmd	[&quot;docker&quot;]

Language features
======================================================

row
 Feature Comments
 FeatureLink ../features/hasComments.html
 Supported ✓
 Token 
 Example
  # A comment
row
 Feature Line Comments
 FeatureLink ../features/hasLineComments.html
 Supported ✓
 Token #
 Example
  # A comment
row
 Feature Semantic Indentation
 FeatureLink ../features/hasSemanticIndentation.html
 Supported X
 Token 
 Example
