Makefile
========

Makefile is a programming language created in 1976 by Stuart Feldman.
 https://pldb.io/concepts/../lists/explorer.html#searchBuilder=%7B%22criteria%22%3A%5B%7B%22condition%22%3A%22%3D%22%2C%22data%22%3A%22appeared%22%2C%22origData%22%3A%22appeared%22%2C%22tags%22%3A%22num%22%2C%22value%22%3A%5B%221976%22%5D%7D%5D%2C%22logic%22%3A%22AND%22%7D
 https://pldb.io/concepts/../lists/creators.html#q=Stuart%20Feldman

#287 on PLDB
48 Years Old
248k Repos

Try now: TIO

A makefile is a file containing a set of directives used with the make build automation tool.. Read more on Wikipedia...
 https://en.wikipedia.org/wiki/Makefile

- Makefile website
 https://www.gnu.org/software/make/
- Makefile Wikipedia page
 https://en.wikipedia.org/wiki/Makefile
- Makefile docs
 https://www.gnu.org/software/make/manual/make.html
- There are at least 247,622 Makefile repos on GitHub
- Makefile first developed in Bell Labs
- The  Google BigQuery Public Dataset GitHub snapshot shows 153k users using Makefile in 251k repos on GitHub
- Explore Makefile snippets on Rosetta Code
- Makefile Ubuntu package
 https://packages.ubuntu.com/jammy/make
- Pygments supports syntax highlighting for Makefile
- GitHub supports syntax highlighting for Makefile
- Makefile appears in the Quine Relay project
- See also: (1 related languages)C

 edit : main.o kbd.o command.o display.o \
       insert.o search.o files.o utils.o
        cc -o edit main.o kbd.o command.o display.o \
                   insert.o search.o files.o utils.o

main.o : main.c defs.h
        cc -c main.c
kbd.o : kbd.c defs.h command.h
        cc -c kbd.c
command.o : command.c defs.h command.h
        cc -c command.c
display.o : display.c defs.h buffer.h
        cc -c display.c
insert.o : insert.c defs.h buffer.h
        cc -c insert.c
search.o : search.c defs.h buffer.h
        cc -c search.c
files.o : files.c defs.h buffer.h command.h
        cc -c files.c
utils.o : utils.c defs.h
        cc -c utils.c
clean :
        rm edit main.o kbd.o command.o display.o \
           insert.o search.o files.o utils.o

#!/usr/bin/make -f
%:
	ls -l

edit: main.o kbd.o command.o display.o
    cc -o edit main.o kbd.o command.o display.o
     
main.o: main.c defs.h
    cc -c main.c
kbd.o: kbd.c defs.h command.h
    cc -c kbd.c
command.o: command.c defs.h command.h
    cc -c command.c
display.o: display.c defs.h
    cc -c display.c

clean:
     rm edit main.o kbd.o command.o display.o

Language features
======================================================

row
 Feature Comments
 FeatureLink ../features/hasComments.html
 Supported ✓
 Token 
 Example
  # A comment
row
 Feature Line Comments
 FeatureLink ../features/hasLineComments.html
 Supported ✓
 Token #
 Example
  # A comment
row
 Feature Semantic Indentation
 FeatureLink ../features/hasSemanticIndentation.html
 Supported ✓
 Token 
 Example
row
 Feature Assignment
 FeatureLink ../features/hasAssignment.html
 Supported ✓
 Token 
 Example
  objects = program.o foo.o utils.o
row
 Feature Variable Substitution Syntax
 FeatureLink ../features/hasVariableSubstitutionSyntax.html
 Supported ✓
 Token 
 Example
  objects = program.o foo.o utils.o
  $(objects)
